apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
  name: multitool-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
      annotations:
        k8s.v1.cni.cncf.io/networks: '[
                { "name": "macvlan-network",
                  "ips": ["172.16.1.10/24"]
                }
        ]'
    spec:
      containers:
      - image: praqma/network-multitool
        imagePullPolicy: Always
        name: multitool
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
