apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool
  name: multitool-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
      annotations:
        k8s.v1.cni.cncf.io/networks: kube-system/example-network
    spec:
      containers:
      - image: praqma/network-multitool
        imagePullPolicy: Always
        name: multitool
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW"]
        resources:
          limits:
            rancher.io/intelnics:  1
          requests:
            rancher.io/intelnics:  1
