apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: multitool-dpdk
  name: multitool-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: multitool
  template:
    metadata:
      labels:
        app: multitool
      annotations:
        k8s.v1.cni.cncf.io/networks: kube-system/example-network-dpdk
    spec:
      containers:
      - image: rparikh/dpdk-app-centos
        imagePullPolicy: Always
        command: ["sleep", "infinity"]
        name: multitool
        securityContext:
          capabilities:
            add: ["NET_ADMIN","NET_RAW", "IPC_LOCK"]
        volumeMounts:
        - mountPath: /hugepages-2Mi
          name: hugepages-2mi
        - mountPath: /sys
          name: sys
        - mountPath: /lib/modules
          name: modules
        - mountPath: /dev
          name: dev
        resources:
          limits:
            rancher.io/intelnicsdpdk: 1
            hugepages-2Mi: 1Gi
            memory: 2Gi
          requests:
            rancher.io/intelnicsdpdk: 1
            hugepages-2Mi: 1Gi
            memory: 2Gi
      volumes:
      - name: hugepages-2mi
        emptyDir:
          medium: HugePages-2Mi
      - name: sys
        hostPath:
          path: /sys
      - name: modules
        hostPath:
          path: /lib/modules
      - name: dev
        hostPath:
          path: /dev
