apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetwork
metadata:
  name: example-network-dpdk
  namespace: kube-system
spec:
  ipam: |
    {
      "type": "whereabouts",
      "range": "192.168.0.0/24",
      "gateway": "192.168.0.1"
    }
  vlan: 0 
  resourceName: intelnicsdpdk
