apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: policy-thebe
  namespace: kube-system
spec:
  nodeSelector:
    kubernetes.io/hostname: thebe
  resourceName: intelnics
  mtu: 1500
  numVfs: 4
  nicSelector:
    deviceID: "1521"
    vendor: "8086"
    rootDevices:
    -  0000:03:00.1
  deviceType: netdevice
