apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-macvlan
  name: pod-macvlan
  annotations:
    k8s.v1.cni.cncf.io/networks: '[
            { "name": "macvlan-conf",
              "ips": [ "10.1.1.101/24" ],
              "mac": "c2:b0:57:49:47:f1",
              "gateway": [ "10.1.1.1" ]
            }]'
spec:
  containers:
  - image: praqma/network-multitool
    imagePullPolicy: Always
    name: multitool
    securityContext:
      capabilities:
        add: ["NET_ADMIN","NET_RAW"]
