apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: ollama-slow
  name: ollama-slow
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: ollama-slow
  template:
    metadata:
      labels:
        app.kubernetes.io/component: ollama-slow
    spec:
      containers:
      - env:
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
        image: ollama/ollama:0.3.14
        imagePullPolicy: IfNotPresent
        lifecycle:
          postStart:
            exec:
              command:
              - /bin/sh
              - -c
              - "while ! /bin/ollama ps > /dev/null 2>&1; do\n  sleep 5\ndone\necho
                \"llama3\" | xargs -n1 /bin/ollama pull \n"
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 5
        name: ollama-slow
        ports:
        - containerPort: 11434
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 3
        volumeMounts:
        - mountPath: /root/.ollama
          name: ollama-data-slow
      dnsPolicy: ClusterFirst
      volumes:
      - emptyDir: {}
        name: ollama-data-slow
---
apiVersion: v1
kind: Service
metadata:
  name: ollama-slow
  labels:
    app: ollama-slow
spec:
  ports:
  - name: http
    port: 8001
    targetPort: 11434
  selector:
    app.kubernetes.io/component: ollama-slow

