apiVersion: v1
kind: PersistentVolume
metadata:
  name: open-webui-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /mnt/data/open-webui
  volumeMode: Filesystem

