apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan-conf
spec: 
  config: '{
      "cniVersion": "0.3.1",
      "plugins": [
        {
          "type": "macvlan",
          "capabilities": { "ips": true },
          "master": "eth0",
          "mode": "bridge",
          "ipam": {
            "type": "whereabouts",
            "range": "192.168.2.0/26",
            "range_start": "192.168.2.10",
            "range_end": "192.168.2.20",
            "routes": [
              { "dst": "10.179.0.0/16" }
            ]
           }
        }, {
          "capabilities": { "mac": true },
          "type": "tuning"
        }
      ]
    }'

