apiVersion: v1
kind: Pod
metadata:
  labels:
    app: pod-macvlan
  name: pod-macvlan
  annotations:
    k8s.v1.cni.cncf.io/networks: macvlan-conf 
spec:
  containers:
  - image: praqma/network-multitool
    imagePullPolicy: Always
    name: multitool
    securityContext:
      capabilities:
        add: ["NET_ADMIN","NET_RAW"]

